app:
  github-repo: nilssonjn/postnord-cm-shipping
  update-check-enabled: true

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: cardmarket-shipping
server:
  port: 8081

logging:
  file:
    name: logs/cardmarket-shipping.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 5

postnord:
  apiKey: ${POSTNORD_API_KEY}
  issuerCode: ${POSTNORD_ISSUER_CODE}
  customerNumber: ${POSTNORD_CUSTOMER_NUMBER}

  application:
    applicationId: ${POSTNORD_APPLICATION_ID}
    name: "Cardmarket Shipping"
    version: "1.0"

  url: ${POSTNORD_URL}
  urlParams: ${POSTNORD_URL_PARAMS}

  serviceCodes:
    UX:
      addon:
      aliases:
        - "Priority Letter"
        - "Priority Letter (1:a-klassbrev)"
    "86":
      addon:
      aliases:
        - "Spårbart Varubrev (Hemleverans)"
    RR:
      addon:
      aliases:
        - "DHL Package size S"
    "34":
      addon:
      aliases:
        - "International Registered Letter (Online)"
        - "[Tracked Letter]"

  defaultPackageType: "EN" # PostNord package type code EN = envelope/letter
  testMode: ${POSTNORD_TEST_MODE} # set to false for production

  sender:
    name: ${SENDER_NAME}
    street: ${SENDER_STREET}
    zipCode: ${SENDER_ZIP_CODE}
    city: ${SENDER_CITY}
    countryCode: "SE"

printer:
  name: ${PRINTER_NAME}
  enabled: ${PRINTER_ENABLED}
