spring:
  application:
    name: cardmarket-shipping
server:
  port: 8081

postnord:
  apiKey: ${POSTNORD_API_KEY}
  issuerCode: ${POSTNORD_ISSUER_CODE}
  customerNumber: ${POSTNORD_CUSTOMER_NUMBER}

  url: ${POSTNORD_URL}
  paperSize: "&paperSize=A4" # PostNord label paper size, A4 is the default

  serviceCodes:
    "1:a-klass brev inrikes":
      code: "LX"
      addon:
    "Varubrev Förstaklass":
      code: "86"
      addon:
    "Brev utrikes förstaklass":
      code: "UX"
      addon:
    "Tracked Letter":
      code: "34"
      addon:
    "Rek":
      code: "RR"
      addon: "FB"


  defaultPackageType: EN # PostNord package type code EN = envelope/letter
  testMode: true # set to false for production

  sender:
    name: ${SENDER_NAME}
    street: ${SENDER_STREET}
    zipCode: ${SENDER_ZIP_CODE}
    city: ${SENDER_CITY}
    countryCode: "SE"
